---

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=djangopass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U djangouser -d djangodb"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here-change-in-production
      - DATABASE_URL=postgresql://djangouser:djangopass@db:5432/djangodb
      - ALLOWED_HOSTS=localhost,127.0.0.1
      # Optional: Create a superuser for Django admin
      # SU can be created weather in entrypont.sh or with docker-compose command
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=bubu@gmail.com.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  static_volume:
